name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: CHECK ROOT PATH
        run: ls -a
      - name: DOCKER VERSION CHECK
        run: docker --version
      # - name: DOCKER LOGIN
      #   run: export CR_PAT=${{ secrets.PCK_KEY }} && echo $CR_PAT | docker login -u amamov --password-stdin
      # - name: DOCKERIZING, PUSH
      #   run: sh dockerizing.sh
